import { useEffect, useRef, useState } from "react";
import {
  downloadOfficeReportPdf,
  officeReportCurrency,
  officeReportTotals,
  officeReportValue,
  printOfficeReport
} from "../utils/officeReport.js";

export default function OfficeReportDialog({ isOpen, title, columns, rows, generatedBy, onClose }) {
  const dialogRef = useRef(null);
  const [working, setWorking] = useState("");
  const [message, setMessage] = useState("");
  const totals = officeReportTotals(rows);

  useEffect(() => {
    const dialog = dialogRef.current;
    if (!dialog) return;
    if (isOpen && !dialog.open) dialog.showModal();
    if (!isOpen && dialog.open) dialog.close();
    if (isOpen) setMessage("");
  }, [isOpen]);

  async function downloadPdf() {
    setWorking("pdf");
    setMessage("");
    try {
      await downloadOfficeReportPdf({ title, columns, rows, generatedBy });
      setMessage("Office Report PDF downloaded successfully.");
    } catch (error) {
      setMessage(error.message || "The PDF could not be created.");
    } finally {
      setWorking("");
    }
  }

  function printReport() {
    setMessage("");
    try {
      printOfficeReport({ title, columns, rows, generatedBy });
    } catch (error) {
      setMessage(error.message || "The report could not be printed.");
    }
  }

  return (
    <dialog className="office-report-dialog" ref={dialogRef} onClose={onClose}>
      <div className="office-report-dialog__header">
        <div><p>Preview</p><h2>{title}</h2></div>
        <button type="button" aria-label="Close Office Report preview" onClick={onClose}>×</button>
      </div>
      <div className="office-report-preview">
        <header>
          <strong>ILLUMINUX GENERAL MERCH CO.</strong>
          <span>Blk. 4, Queenstown 1 Heights, Brgy. San Luis, Antipolo City</span>
          <h3>{title}</h3>
        </header>
        <div className="office-report-meta">
          <span>Generated: {new Intl.DateTimeFormat("en-PH", { dateStyle: "medium", timeStyle: "short" }).format(new Date())}</span>
          <span>Generated by: {generatedBy || "Employee"}</span>
        </div>
        <div className="office-report-table-wrapper">
          <table>
            <thead><tr>{columns.map((column) => <th key={column.key}>{column.label}</th>)}</tr></thead>
            <tbody>{rows.map((row) => (
              <tr key={`${row.companyId}-${row.id}`}>
                {columns.map((column) => <td key={column.key}>{officeReportValue(column, row)}</td>)}
              </tr>
            ))}</tbody>
          </table>
        </div>
        <div className="office-report-totals">
          <span>Total Amount: {officeReportCurrency.format(totals.amount)}</span>
          <span>Total Unpaid: {officeReportCurrency.format(totals.balance)}</span>
        </div>
      </div>
      <div className="office-report-dialog__footer">
        <p role="status">{message}</p>
        <div>
          <button className="secondary-action" type="button" onClick={printReport}>Print</button>
          <button className="primary-action" type="button" disabled={Boolean(working)} onClick={downloadPdf}>
            {working === "pdf" ? "Creating PDF…" : "Download PDF"}
          </button>
        </div>
      </div>
    </dialog>
  );
}
