-- User passwords are intentionally not stored in this SQL file.
-- After running the schema, create the first administrator with:
-- npm run create-admin -- admin "YourSecurePassword" "Administrator Name"
