const PHP_NUMBER = new Intl.NumberFormat("en-PH", {
  minimumFractionDigits: 2,
  maximumFractionDigits: 2
});

export const officeReportCurrency = new Intl.NumberFormat("en-PH", {
  style: "currency",
  currency: "PHP",
  minimumFractionDigits: 2,
  maximumFractionDigits: 2
});

export function officeReportValue(column, row) {
  if (column.reportValue) return String(column.reportValue(row) ?? "—");
  if (column.key === "amount" || column.key === "balance") {
    return officeReportCurrency.format(Number(row[column.key] || 0));
  }
  return String(row[column.key] ?? "—");
}

export function officeReportTotals(rows) {
  return rows.reduce((totals, row) => ({
    amount: totals.amount + Number(row.amount || 0),
    balance: totals.balance + Number(row.balance || 0)
  }), { amount: 0, balance: 0 });
}

function filename(title) {
  const date = new Date().toISOString().slice(0, 10);
  const name = title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
  return `illuminux-${name}-${date}.pdf`;
}

function escapeHtml(value) {
  return String(value ?? "").replace(/[&<>"']/g, (character) => ({
    "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#039;"
  })[character]);
}

export async function downloadOfficeReportPdf({ title, columns, rows, generatedBy }) {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 10;
  const tableWidth = pageWidth - margin * 2;
  const totalWeight = columns.reduce((total, column) => total + (column.reportWidth || 1), 0);
  const widths = columns.map((column) => tableWidth * (column.reportWidth || 1) / totalWeight);
  const generatedAt = new Intl.DateTimeFormat("en-PH", { dateStyle: "medium", timeStyle: "short" }).format(new Date());

  function drawHeading() {
    doc.setTextColor(8, 8, 8);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(15);
    doc.text("ILLUMINUX GENERAL MERCH CO.", pageWidth / 2, 12, { align: "center" });
    doc.setFontSize(8);
    doc.text("Blk. 4, Queenstown 1 Heights, Brgy. San Luis, Antipolo City", pageWidth / 2, 17, { align: "center" });
    doc.setFontSize(11);
    doc.text(title, pageWidth / 2, 23, { align: "center" });
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7.5);
    doc.text(`Generated: ${generatedAt}`, margin, 29);
    doc.text(`Generated by: ${generatedBy || "Employee"}`, pageWidth - margin, 29, { align: "right" });
  }

  function drawTableHeader(y) {
    let x = margin;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(6.8);
    columns.forEach((column, index) => {
      doc.setFillColor(255, 222, 164);
      doc.setDrawColor(8, 8, 8);
      doc.rect(x, y, widths[index], 9, "FD");
      doc.text(doc.splitTextToSize(column.label, widths[index] - 3), x + widths[index] / 2, y + 4, { align: "center" });
      x += widths[index];
    });
    return y + 9;
  }

  drawHeading();
  let y = drawTableHeader(33);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(6.6);

  rows.forEach((row) => {
    const lines = columns.map((column, index) => doc.splitTextToSize(
      officeReportValue(column, row).replaceAll("₱", "PHP "),
      widths[index] - 3
    ));
    const rowHeight = Math.max(8, Math.max(...lines.map((line) => line.length)) * 3.4 + 2);
    if (y + rowHeight > pageHeight - 18) {
      doc.addPage();
      drawHeading();
      y = drawTableHeader(33);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(6.6);
    }
    let x = margin;
    columns.forEach((column, index) => {
      const numeric = column.key === "amount" || column.key === "balance";
      doc.setFillColor(255, 255, 255);
      doc.setDrawColor(8, 8, 8);
      doc.rect(x, y, widths[index], rowHeight, "FD");
      doc.text(lines[index], numeric ? x + widths[index] - 1.5 : x + 1.5, y + 4, {
        align: numeric ? "right" : "left"
      });
      x += widths[index];
    });
    y += rowHeight;
  });

  const totals = officeReportTotals(rows);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.text(
    `Total Amount: PHP ${PHP_NUMBER.format(totals.amount)}   |   Total Unpaid: PHP ${PHP_NUMBER.format(totals.balance)}`,
    pageWidth - margin,
    Math.min(y + 7, pageHeight - 7),
    { align: "right" }
  );
  doc.save(filename(title));
}

export function printOfficeReport({ title, columns, rows, generatedBy }) {
  const printWindow = window.open("", "_blank");
  if (!printWindow) throw new Error("Allow pop-ups to print this report.");
  printWindow.opener = null;
  const generatedAt = new Intl.DateTimeFormat("en-PH", { dateStyle: "medium", timeStyle: "short" }).format(new Date());
  const totals = officeReportTotals(rows);
  const head = columns.map((column) => `<th>${escapeHtml(column.label)}</th>`).join("");
  const body = rows.map((row) => `<tr>${columns.map((column) => {
    const numeric = column.key === "amount" || column.key === "balance";
    return `<td class="${numeric ? "number" : ""}">${escapeHtml(officeReportValue(column, row))}</td>`;
  }).join("")}</tr>`).join("");

  printWindow.document.write(`<!doctype html><html><head><title>${escapeHtml(title)}</title><style>
    @page { size: A4 landscape; margin: 10mm; }
    * { box-sizing: border-box; }
    body { margin: 0; color: #080808; font-family: Arial, sans-serif; }
    header { margin-bottom: 12px; text-align: center; }
    header h1 { margin: 0; font-size: 20px; letter-spacing: .08em; }
    header p { margin: 4px 0; font-size: 11px; }
    header h2 { margin: 9px 0 0; font-size: 15px; }
    .meta { display: flex; justify-content: space-between; margin: 10px 0 7px; font-size: 10px; }
    table { width: 100%; border-collapse: collapse; font-size: 10px; }
    th, td { padding: 7px 6px; border: 1px solid #080808; text-align: left; }
    th { background: #ffdea4; text-align: center; }
    td.number { text-align: right; }
    .totals { margin-top: 10px; text-align: right; font-size: 11px; font-weight: 700; }
  </style></head><body>
    <header><h1>ILLUMINUX GENERAL MERCH CO.</h1><p>Blk. 4, Queenstown 1 Heights, Brgy. San Luis, Antipolo City</p><h2>${escapeHtml(title)}</h2></header>
    <div class="meta"><span>Generated: ${escapeHtml(generatedAt)}</span><span>Generated by: ${escapeHtml(generatedBy || "Employee")}</span></div>
    <table><thead><tr>${head}</tr></thead><tbody>${body}</tbody></table>
    <div class="totals">Total Amount: ${escapeHtml(officeReportCurrency.format(totals.amount))} &nbsp; | &nbsp; Total Unpaid: ${escapeHtml(officeReportCurrency.format(totals.balance))}</div>
  </body></html>`);
  printWindow.document.close();
  printWindow.focus();
  printWindow.print();
}
